apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - authentik.yaml
  - cert-manager.yaml
  - grafana.yaml
  - longhorn.yaml
  - metallb.yaml
  - podinfo.yaml
  - postgres.yaml
  - traefik.yaml

patches:
  - target:
      kind: Kustomization
    patch: |-
      - op: add
        path: /spec/interval
        value: 10m0s
      - op: add
        path: /spec/retryInterval
        value: 1m0s
      - op: add
        path: /spec/prune
        value: true
      - op: add
        path: /spec/sourceRef
        value:
          kind: GitRepository
          name: flux-system
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
