apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
spec:
  path: ./k8s/infra/longhorn
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-resources
spec:
  path: ./k8s/infra/longhorn/resources
