apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-operator
resources:
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/crd/bases/redis.redis.opstreelabs.in_redis.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/rbac/role.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/rbac/serviceaccount.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/rbac/role_binding.yaml
  - https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/v0.18.0/config/manager/manager.yaml
