apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgres-cluster
spec:
  teamId: none
  volume:
    size: 5Gi
    # TODO: Look into better options (e.g. replicate to NFS)
    storageClass: local-path
  numberOfInstances: 1
  users:
    postgres:
      - superuser
      - createdb
  databases:
    postgres: postgres
  postgresql:
    version: "15"
