apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
namespace: postgres
resources:
  - namespace.yaml
  - https://github.com/zalando/postgres-operator/manifests/
  - dbms.yaml
