apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-operator
resources:
  - https://storage.googleapis.com/tekton-releases/operator/previous/v0.72.0/release.yaml
  - tekton-config.yaml
