apiVersion: v1
kind: Secret
metadata:
    name: trmnl-laravel-app-key
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:UnmZNQ5KqXrUonpTwGK3xspuKFI87yBbOfS+5Aa2egmCIOsNCdNccb60Rzfe7U2oBZDL,iv:L5CuQvorko9F6AcuPwQaI0LPfUFWcR/Lcndf/vv15+k=,tag:9j5zaHUVyJTJW7ARYNIm6Q==,type:str]
sops:
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRDByd3hkbzdSbHZFcW90
            eThVSGN4bi9YRHgrTVRGME1jRkVqUkx3SXpBCmFvQ0M0Q0wraWZDUzlZVkp4YkM4
            K2N4NHIzZTgrZUQxVFpTbjArdWZ1NmcKLS0tIDRNRFNndUtTS2xkK001VmwweUlx
            Z2FCMGlqYkI1U3JVYUFqUFJsUlhvbkEKz7XaFvtVY5LWZ0ZWkoHXw6eTFkEBNi0G
            G7nigMBS1yFZq3dwv6xtBk4T3DJVbCbyt0jEUJ9hAT2LpcP0mZkl7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:46:10Z"
    mac: ENC[AES256_GCM,data:SiwQN77JXc3znZqPhioHTCMAm4nGMGEPswmxQ4kQLTE2BoMLdBlDzw8X8P2x7WBVCBej2B6q2swZKKLCxS4U0csUT6ZsArTxAV/noeimO4ZAsp5Ucv0hcqto1svS5dnDec6aeQAq2ZgphClRiyWEvdu+/kVdlu/kIQN6SIpBfVg=,iv:6TxF/TojEsZXFIUq0gTtD48edPmG4C6KgaXFS5OvA9Y=,tag:IyAHaqSkm3lMfA3VJurR5w==,type:str]
    pgp:
        - created_at: "2026-02-19T22:46:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoAQ/+Iq6QfizOxNT0cnn1dUO/FcxrLWTkzJOcvi1rxuMRS5Ss
            iKGF31MBoWI8aPqVcoCe8Ze59UxVVtwe4Up8Nfny/OXe0n3zgBkQwGJ4KHMJsWVl
            UkIThTn/ZqeBZj+rBZup3Fx7/cHAIJg5dpbsv9ObNUTdByiQ6n8AHPtBmGnei5g0
            0yZJ80yoDJdW4GCeUBvCbsjJcVgEan45TrCly60GvoPgdF0U6UuGQzhquocwKP8O
            9vr3Vj0dU4MbDgQd2sRKp2Aw2amsxKI6b+tZbkgFQrcG5t15mIQvMSnmAn90jkNl
            b2hukmycbYA9LvYQvePyVY0Dx7qZ1nxSdz+ghXfAXl+kFd8ZffrBKQc56A2h8VGj
            5Xnk75KWLCmmmGVp5T/QwlHmgA6FAe6QgZkW5J81fZw+PJhBsSxO8ka8u7+Z4g/Y
            tq7EYNP3e3fGUaLAQfWrULoMVa46ZNZeKYnDtfR5vbHob5c1N+BRSyNbnEapj8r3
            Uk4yid3C4Im9knXU6LujyIE73CN1GEzyecMBUGdR1u3+ucZwWspgcLLvYAgsicyS
            L4KiOLSrTdpIeeOePJI6VXXmSIamUbJ2zPHoASBGe+ZUPKFGSr2RJnlogw4oJ4Hj
            iZZ0vY5RITQKt+UXoSJYVEkv7qctzDfYRVrfEeUrKUhVyJeJbhpZo4OgnvZjVY3S
            XgHVDk7eu+gsbsB4WkB5BUN5TzCD7r3fiWLe4f1IswFsv/AMg3XMiIbu8e0PIMK4
            VJEmznK2U/p0LnVwnrNDpSVZTq36Tb3HcSaE3iUzaBFUhB2YtSy0UnPmyljnFF0=
            =CYpt
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
