apiVersion: v1
kind: Secret
metadata:
    name: terminus-app-secret
type: Opaque
stringData:
    APP_SECRET: ENC[AES256_GCM,data:23SO0eFeBBp904y4JFZUiAk5YD3eB7UgCPFGBtdw0tvOOjJyBiJG+2FahWIRfVpKMPGP/3fogACEthRAynOmRQ==,iv:M4z2eK3ZebeOz4FYA7raiqrKjWRAHOY9D6vqu1rxCQM=,tag:4EkSG5NyiE9QSZ+ZA6F/1w==,type:str]
sops:
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWldPd0h4djlQcXJoNmU4
            LzZOdnV2Mmo1ZnVtOCthL1o5ZXk2SHZQaXhBCmpwOHBhTXZyazZnV0xqS1Jjc21p
            T2t3TC9nc1RiM1VPSmR0dkxyNjZ3M0kKLS0tIEdrc1IwWkJKSWt5ZXYzNVlDZkdC
            T003U25HNVFQQjdIdW1iY2d3aGFaQUUKSxISaCNOid4ZHa5HBT3OSSng34P2UnOb
            D6aFXLvWH/TUkOotKTnt6bWmN0tw4M1weYu7KpsAmtFnaCLhAnHVkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T21:11:52Z"
    mac: ENC[AES256_GCM,data:r0XBADAJf+DV4shyS4AktImJyr0r9ZEhN77/CqK4ZmnJyzW/64s5dV3ICbDVX0TJMXG8h0R0Cl6GcZEENV6HiXJH/wh0SZ2+JrsEqvWorUp4NUipu/NgT2pkkJS2m6z6q3MaKOpI6ceyBsYXYrESS3XJ9tcqu/85IcQxs5a+9QM=,iv:+gN3w5cGGzaKlXe4jKrz1GTlyjvlLqEbC0R22v0IMoU=,tag:1Zc5V9S1zyXnektlrX/g9A==,type:str]
    pgp:
        - created_at: "2026-02-19T21:11:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoARAAruuNNVALKlk9E7mcmtWH1GbeJE2QYcSIo5p8LZLeXYDS
            1LYJs3mWH6oC7dihTU51vbEmJ5ZzIgRuvOu00EM4bnvshpDw+ysRpH7Weguyd49m
            7vTgT/zhXPLFrDq5aGjIGKdmdDcVI9jR9sw0OhmZ8Ki2Guoi8oSQ1c1xKGyXShw5
            rC7bk9NFis3NXFZ9PVtVTKWfMA4/n9MyLHzrjYxm/+HexwTUoeS7p/36xINuMBre
            Xgy94R+VFGpIFEMaB1KwIw/2FoLahK9px9Z8qr/aUhjo5CnD7WMDdXmFPE1Aqrgd
            Pl2mR0/WU7mWZ5mv/3woW+98GyEADPUUlJw2GfVxrzov4xTsYOS9OFZKR0WCJ0GE
            OmzuJZmv8mmfFTEZwsMuMkp9x9byNLnzMFp+ekGJSvD0g8JkXkxR1eOjEQnLo7Vd
            zF0o4G8917mdXGLeunEO+5Pi5gJr3TIcatUM6O7+x2lI9mbMayWLb611x5rh9sZg
            Km0up07Gztv1UIDNcVOxKw0JfMMuwSpyWZ+h1XlaIJeL6E9LnEW6Sm5d6LjtiZXG
            b/klOEixwXhfcP8O40OSwwBnecbhr+NMeY2Z/cER3tnBRyb/eaOcFm92M5woezC7
            grLca6hPWpiNJb+ls4E17TB96/uxie+poyVMBn9ThzMJyim2lUKqt8zwVTg43YPS
            XgFGuDkVpz8KPgrV39LcxfGdm3Jvc6NrcPAb/rMKDBXYQppkYsDzj2oKBJK7ZncE
            7xcxprHQCGYuRwESwTBHKrgZgavw+nTq9tDs/3ehPN3y1L+QyIIGFxrEcCmoKc0=
            =1XsM
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
