proxmox_api_url: ENC[AES256_GCM,data:/ZP3Tp6+iG5a8FC/ix2XY344KNVspimPKxUEIKvfBtLwFA==,iv:T3HQWrnGWNj+bgr5rgzTauSLGEpBQbc5/MU6QiAtv3Y=,tag:7XofnjhRQUuTxPBGAP5RGQ==,type:str]
proxmox_api_token_id: ENC[AES256_GCM,data:kPMbPSGVxKvfV3zaFzgatUtDmOXdEK5y2/st57s=,iv:viiCIVAd/3PIkMFECYuHGfBiV28a8GVYb/e0fIgTuPc=,tag:PDRdQRkc3GvqLSoH5/g8ww==,type:str]
proxmox_api_token_secret: ENC[AES256_GCM,data:wlFbKq8PQjpz47O2/lpY/KVFgHM/Ldt5+sF1nD1nxScp8hB/,iv:6Ral5xp++HSyt6j7LXH6/4a2N6lkZeIrGmcPfaIj4ig=,tag:VOLbR9PiYCPj1gRqNLm9xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-15T20:30:00Z"
    mac: ENC[AES256_GCM,data:NFYNvN/RFmmW1X5u9Fr13QB0lIuTmbbOj/QZrNCWzFruLyN83VW6qpF+j/zdMEstrnAB2Mo9oUe2RcyWn/o3kz59kMi9TyQvN8ZWiTEf37K61m399pKW6w1quG+M8Obgj5usuOT16ii0F78hpZPJO9zre6gPKDaSrdiyoIZYgsM=,iv:Q18UcRnovPvP3gOSUQbPyGdErRKemT+aRNblIufFfo0=,tag:gCw42MVCfS/DxAJITgVxtQ==,type:str]
    pgp:
        - created_at: "2024-04-15T19:44:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoAQ/8CHvbeTnYdSVVJfuJMCFLLMjL8gn90cEduO8iw+SMeGDq
            i07ujQLu7cXH/e/NHIZ/NEWf45dNlgzDRAqCArfPfTiDnIwrXlPPiTyH8FDMWMV8
            RKdfRS4NidqcyxO48P3kMzm3FVzD3MJE9ZeB7dAtqxfqInUD+rFCTSwiWfGuJ9zU
            7PN7IXAfeS1J7RDSUPQqcAe9gGpKEgNN26vLcXGlSA73HQjOCTnDMPmwt7y9XJjz
            VAPl7cnXft36O7DKY+PXAJhD1LwphZsF+km/R9zMW+/5lcM2+/KHtvgpxm/UDCPP
            RfM61S+0pQLh/iKtyL9kXWbzJvmN09zw4rUVQzt69IL4CeHkgAoRzlgkhwieNB88
            fW0QgRmX/kREXQsWpzmix8kLrWipfiU+sRDuaXQvyFsAW4mQD4gr6l6Pe1m2Rejp
            ckgCeD/+tZn1AVGEnayj4H7WZ0IorYYqsPzF0sQiSVl3mJEN7jEmFRTDO2d47Uh/
            1oM86rmfszuCMdwUgIgJ/XisIgafbLD69XE1gQwLRl+51DsCfP+PqyP7+6OgVm4V
            ZVIHLgfV0vdrQuih0mB0gaz+/Sre64brfBD2srNmjcxSeGy2ifvmI+GaU0WeLZTf
            +Ua/BmUKsq5G41xwGpZ6NaRCQ/MWw7ooRnJ73FWpmJhwsKJqYR/4BDQfdyy4NGTS
            XgF6YkYpp353UnxWLBn1Ns0bW8oBGghU9HFudyzmmHXb0eeav3khgre5BdsURDM1
            XYDSGo8qJMJDUBoRk2aHF9YX8vihYeZ/kZh4LGFej9XYf3aY0gdW85wQhIV1xoM=
            =KDx+
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
