apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: 1.14.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 10m
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
