apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      version: 2024.6.x
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: flux-system
      interval: 10m
  targetNamespace: authentik
  values:
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - auth.s.h-a.cc
        tls:
          - hosts:
              - auth.s.h-a.cc
            secretName: authentik-tls

    postgresql:
      enabled: false

    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi

    global:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret-key
              key: secret-key
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret-key
              key: bootstrap-password

        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-app
              key: username
        - name: AUTHENTIK_POSTGRESQL__PORT
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-app
              key: port
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres-app
              key: password

    additionalObjects:
      - apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: authentik-postgres
          namespace: authentik
        spec:
          instances: 1
          storage:
            size: 1Gi
