apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/grafana/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana-operator
      version: v5.12.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 10m
  targetNamespace: grafana-operator
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
