apiVersion: v1
kind: Secret
metadata:
    name: browserless-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:npE65T1Y0q41gO/uCsbaAu/DPf3DN2rUCB2+EDATCNi5NPhZ,iv:+rLxU9PGbxHeDD8kt8O8+Hldg2z3MB7pyWXGV3WiqxQ=,tag:tucJ46l44K7GQpwJ3i2ryg==,type:str]
sops:
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cTg1bElHK2EwUUQvRE1V
            aXVTSytXbDA5VG1MUEMweFR1dHkzQjlJOVc0CjRBMXdCUmZ2eTVWd2w1OWJsQkwz
            aEQ5eW9HZEcvbWsvd2NscnpjZUVWUmsKLS0tIEdDZnBVdEhEYW5jNmNxTHpBdFBF
            NXUvRlZyMHNaN3VJdUFSdGJidC9GSTAKcRHYg6w6JbngeAFQPIkN46jhcncA9GEr
            S+gopv5mapArYm9pgiukmDViU6DeVbHR4QZgoodet6bY6W6EZayjrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:37:53Z"
    mac: ENC[AES256_GCM,data:83ikVfCidMELdwf70k6y7O7Quuo8rMYwYvU2VzMmzqJMRbZgLZU+Dd0X/NNkLYim19ZpmR7aHaoHPKkRWv9aXexRgZaFL3vQi1cqv+mlwYe0UeoB0H/70WEcXhOQV73Sju/t7busrWs7ocZRjJl1RaKz1o1tnT/joKvc/ex14Ws=,iv:rUi4GnVWNMT3l1SZ78h717Vu0Wv2PgNmQhm85iVGxHo=,tag:xBq7xN9VHra3Wf8W1nTKNA==,type:str]
    pgp:
        - created_at: "2025-10-31T21:37:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoARAAhc0TOuvGIYgLsqhXQxAzJ5RzIi1t12cvMIh8w1gZo+xM
            6kiO5T3ZJHfZi7vua5BD/vvfCfvtk+2L/PsqKNDEKhzKkg1ZO7hvZh+m1D1/wduV
            c1dLxHhZJ9h5Xe4SNU2KAe0kApNVyc/STKnaUT2AbnXIqxOCOmulD7exU+KYgGCp
            NNZWiQ0SWQcA7TwJMAgix4umq51Fu//Hs6HEY8J3YpRN3AOatiLTtF1WlMAdzKIO
            QuoU/DllIZT9jYa9RV12pect0iXnCqeQcdrnWAVvYK74O8a3WNDjbWQsX4lDUZLZ
            ZPb3g0nVPtXHxtAkLyb+z9sYEqz7CbNFyMKQs22Ev8yMKXvWg2ew6CjlKKbyoJCD
            jdxyNvVvctngixEafpWC4k/xjcbdDtdvplKEuel42iBmvydkw51eR/sNUNqe4yba
            oDiKkjj//ho7XicKlwo+k6or3emx0bMC3jpb+gkl+WxqmkHoXV4cMjEgputvpuSQ
            8fBArhg+h6cFVWnvJRZMK4VKxQWWvkMjvcXtV1DYkS53kC23ODPcVR+Sc0zDp9ni
            2lAS4Fd2d2RqpUGRPa7cvJCWVgUiEhbRCYHLKmPv5lvLLmyRSdTjhuRZlPUQrwQE
            bfWyLqbi46DDk01UYXJIcAUt1t3UOMptluL0QOokDLnPcYkxFs/+HvqN/r7BJlTS
            XgHxjoG/XMSr1Fvbx+ASsg8RXNK+Cfaoa5BmkgA7OEnP7C70ky9vMTUQLKy1TPpx
            dtQXZmyZnE6ZZBGCDQGL6R1hcaAEa22EK+D3fO6K5RwS6joyLvqEfY20lTysTPc=
            =+ylB
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
