apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: n8n
spec:
  serviceName: n8n
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.37
          command: [ "sh", "-c", "chown 1000:1000 /data" ]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: n8n
          image: n8nio/n8n:2.11.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443 # yes this is still plain http
              name: http
          resources:
            requests:
              cpu: "1"
              memory: "1G"
            limits:
              memory: "4G"
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-app
                  key: host
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-app
                  key: dbname
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-app
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-app
                  key: password
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-app
                  key: port
            - name: N8N_PORT
              value: "443"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_HOST
              value: "n8n.s.h-a.cc"
            - name: GENERIC_TIMEZONE
              value: "Europe/Vienna"
            - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
              value: "false"
            - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
              value: "true"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
          livenessProbe:
            httpGet:
              path: /healthz
              port: 443
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 443
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
