apiVersion: v1
kind: Secret
metadata:
    name: discord-bot-secret
    namespace: featureschleuder
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7CTqbUiludjZ3K5pJ2CmlUoaKJF+DdeOslNgQF+s8KLgO3ThuUwU4QfJfB6Oz32yDG2emBcWjBX6g4gbr+xQig==,iv:+l1kujNw/s3PQ17V6ll10I+Fd26K/Aw/V7tj0gyDDP8=,tag:Fyg4MgQ/PrEI3XaC/FoaxQ==,type:comment]
    #ENC[AES256_GCM,data:9C9XBj5bIkQ5DHVvt1CTCvotvA6+crbX8Wmb3m2YUxZm3CofI0bfNZdK3spZ6LaHkxWDaUIaPbt+2imPUT4=,iv:3PIgRxKkwc3mjEB11npL+EkrVcoj0QTPMd3Zj/RXc4w=,tag:LZbosBzxyalo9s2o88fk6Q==,type:comment]
    #ENC[AES256_GCM,data:ZCpKBh671Q/a7EBwhGCXJxDPJtuTdCt5oXymdmjSJfNDpQTwWHGAcs8Wv8WYu5rPIfJY,iv:Hk9lfiaQD8zJ3V39zUdnt95urepIuHjM5PEADkUgEnk=,tag:4XMCrWzBw8NCjkW9GnVUaQ==,type:comment]
    #ENC[AES256_GCM,data:Q5awDxu6hmyHkTZrfJjk3zlYpJnq/LL5ue0FvHVPyi1yJmYs/lzZhuO/jvkI/pONDRh6,iv:lEX6rbNCn0TClWHQHvzplmbCYeZ5vPJBFdHxPhZtFbw=,tag:zEnUmM7NlMmUcZQvsWnjZw==,type:comment]
    #ENC[AES256_GCM,data:EkSOBbw89mPloegwf27n55g9ZygVW2w8yHWqtL7OBEfF6BpkLej6Xd5H+3DbMCs/9g==,iv:gGdpbmm8jZxRAN7kAXaGGFesAmmorRKMsMrCUWYbxEQ=,tag:sY1/DFeImS0rXRlPrJhw4g==,type:comment]
    #ENC[AES256_GCM,data:GEnKjVI9YUBSVt1s0mImCUHAH1Pk7B8TNsySEpNfcHt/iwIBtSXxEx11ZS730XUbGA==,iv:wj15xQp1PJYONjhNSGOMwtgM1CR2SGFOCSuqdAKm9yM=,tag:oQ2tQHH6wx6asth3tkxQHg==,type:comment]
    #ENC[AES256_GCM,data:TXcegvhUBMEmILjsG+EZ5cM=,iv:O+eJRxoa21Lc4kKHWvLhGFQjwJek26FtxSEuQ1no/kE=,tag:2rhjeL4NAx06zMlEOZjBgA==,type:comment]
    DISCORD_TOKEN: ENC[AES256_GCM,data:+aH+ruOm7AZPDZJT+ymzsWndGKZ4qS4fBj3aW7H+dVo+U6mMNwn26oHZ/64rtzbJTAknXcHJgU1Ah0t+lKLfuWpWZkOVUWmZ,iv:YSdkaDj6KHl94Bea2d21VpqqgXKqwSTsM00sv2Uj070=,tag:GPXPt3Xyj/zALPaPEQGvFQ==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:gCLIumHs2ResyFra3Ws2ZdOG6w==,iv:LxIKHn+kF89+0qTMS/vukRggZuh3Kk4bAo/WeYfRkUs=,tag:WilXeu8PW9M2FDUa+nFk1Q==,type:str]
sops:
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYWpTbTg0RjhzTnFMS09o
            WjI1UHVzZVNvZHpkQjc3THliL0JPV3FqekU4ClY0NVFpQ2QyS1hMSlU2Zys0c20w
            N2NqdEdCQ1JXUUl3ZkdZd1RBbG5UR1UKLS0tIGNlTk5nS3FQZWNvSFNWdzhvcHYr
            TkVrWDJJM2MzUXJ3NXc0aDRQaDBlZlEKjQBnYT6aC5phuVZSR4xAx5I1uKO5jdj8
            SIk5lkHY0BUSRxlO0OptrJaTcmBwaVtvnxoKFpU6+r6FLooCK/NA/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T08:55:48Z"
    mac: ENC[AES256_GCM,data:jJjDGU7OpMtMRhG9unAzw8QUidJKWDih0KzIKTvCXCuARZ3INtVqdCHQnHh5oDnZnsyQUYjIOy5HcUp7syFWzNN7hxKHlxkfa9k3+/zVGrxvtDGo1Oqdw5/S16MF1FxBafdvnLxY/jwu7fqLzlD6fA7IyLA3fZtbBa7h6t3+cHM=,iv:jzZiACp44yPltQaDYzbBeisj7C0lphpF00peQpVx0kw=,tag:WDhpgKMCpL4fCWVUQ5i79g==,type:str]
    pgp:
        - created_at: "2025-11-23T08:55:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoAQ/+PcgK0htp3lAl3M/Rh6q7/GnHk9+IAanOA4HEaM3gi2Hr
            sHrWMw60chNwtM5uD4HYY5rUS0cPtBwyaaFeqIr8iOXM9tczyx7+fQOnJUyKWlx6
            gvhtb8oGeac6hKR3p7qfX3NkGTwtWiaNITfogCaYJRqXwftPP3FNcSLewna1Wyzz
            Yf49+vnyqnFuokdVCUn6UMyKG3FGEERallxBMKa1PDC/8p5emlAwLWeVsaq8qwxP
            IC9+b0BjvdoAXP01Thi19ZR6G/Im5/1LgYUfWolyp6r/+KgF/SCvnr+Fn9Hf76TY
            jFCRQHcoIOR0fazZu0aXQEOrq1nHHZ+ejOghr3PHq6FmkKY4Xn+uaQojNikdejXZ
            FCESK/XPNVVzgDuEYE763z0/RYC9I21b3GBVUwhUvAvk6rqaQncwuOvFf+ZbYY1l
            3igtj0omEcHC1zmq1KJ9pt62MST/G43Nx16iBgqVF3gG5qoVVF110FT58DNqDWck
            yKFi7jBfOSUFxruLv+fAFACBlIpBdHyTDBSdDZ/OsXsfv0fCAW92mAmLT7fFOH67
            KW3Ehq9NQt985CWDcOqQr5lrTbJeI3Rbnvnv6r2bWZdnRSlPwF5c1fuERmixCDjF
            EklkD3o7ypBioCUfF5Kup3pY1a/QhGKAVNSwWNiGCoFqX/0iY4Co+05bKCfY3ajS
            UQFFPlvG60yyI4wlyBsMPbY7nQj9RhZV7webLi4xKqmiIagb2DfMLMbvauZm5Xwb
            E3Io25A82Kq7f0c7T4wIjPFgNo2mGCGDGb/odmGRFd/QEw==
            =O2CK
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
