apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 27.0.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 10m
  targetNamespace: traefik
  values:
    ports:
      web:
        redirectTo:
          port: websecure
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.s.h-a.cc`)
        entryPoints:
          - websecure
        middlewares:
          - name: ak-outpost-authentik-embedded-outpost
            namespace: authentik
        tls:
          secretName: traefik-dashboard-tls
    extraObjects:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: traefik-dashboard-cert
          namespace: traefik
        spec:
          secretName: traefik-dashboard-tls
          issuerRef:
            name: letsencrypt-prod
            kind: ClusterIssuer
          dnsNames:
            - traefik.s.h-a.cc
