apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 27.0.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 10m
  targetNamespace: traefik
  values:
    ports:
      web:
        redirectTo:
          port: websecure
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
