apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: librechat-repo
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/danny-avila/librechat-chart
  interval: 4h
