apiVersion: v1
kind: Secret
metadata:
    name: librechat-secrets
    namespace: librechat
type: Opaque
stringData:
    #ENC[AES256_GCM,data:oaqKR/W6l/PprjICMLQBdD/N1EPIPuV6c3+/u42WA/M=,iv:prjBvxu7xJj8qLxq7ll3DMNrxIvTpe7r8DpWzWYkOI8=,tag:qAov9mhwFzwVEYtmnlWROg==,type:comment]
    CREDS_KEY: ENC[AES256_GCM,data:R7rxuLEFs0Kkjc+UnRM6eJDBELEDhpUNOVcncFgQ0JLW3PSWmt07f6DHwGYg0TIaHeYgyFfeIwj88X6SfH+zTw==,iv:wy4NJ8yFNhoYGnFOrdqKhMp/973B0RMgXWtq7SECoks=,tag:twxutQmXBxnZrJCKIWZ9Ag==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:dsEMgfCVYcRJcMjAJmshyYiobjt2RhKilUKyrwbVRog=,iv:punccgY8/sCw46i3Tn0NNI6SsaXwrZZjf/+DHi9S+JM=,tag:bb92L/qFd4klpXoGeOylLw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:b6O27MctfXA4cTzO6Nl7eXQzK+K/RY/doUr+UPG9WyknN07jYvntGVYbDrUaSYCJvvW+ZcliOwZhMZpnWXfT2g==,iv:Y4d/xBgtBGJxsc8fyUqvGwAhBs4xzJduF5Vk/C3dTlg=,tag:ksubLqtUCiVjR5V6GBQ/hw==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:ULA8hflVrUfAc3OQExhBJeO+t/+cx2S1j3UrK4e1PLQd6aBnHmIp5vvEKIwQp5ZnkhLcRcx+OAEskL9lMW+aww==,iv:oWEosQvTVcUOpsDJ1xX9ELWWlk+BLRUWtqdflCLnqgQ=,tag:2XfJlZhNOJGWoWXgxYuF0w==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:TL0FhtR5t50qmorK3GX4LWFtEluE2fYMepqOWcpeHxo=,iv:XLWQhQVgYmUcYQZpExpjl77MLv5VzCtHVq2BnI1tB7g=,tag:p8GA6wN6I7CmDVau2jbUKg==,type:str]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:ysF14ejk8uUor9i78/ebmlCYAYdinkkGn3mlPeTQumM6lK6fX7AfWQ==,iv:/X1hXnUsjiGGCqny2l7G20YcTWss/8fL2xJAITdZ3gE=,tag:RJ2VMy7RL5/ic9sSnyQK7A==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:iTwKy4gvbUjWH/6BDW87IFrrc2bD5Li9JMrKVt0YB3Ar+M5UH/qqJeQn71k08/gpxC8Tqqld/2JXNS290z+lLNCcYjvs9VAL7ZQpGsV1aulqrY8e8MXMj7SYmrsPzXwVq+KX0PoJF5RMvY09odhJF7YFsiQlcBGdZE6ITiuBAqs=,iv:uIxFa5CwjRncv8zrIolivSWA9/Ts5i+BGtVB1rkpz1k=,tag:jmIACwoOMZ0VoU4bEOM3iQ==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:m2ThV0rDnf4zIdrSnsjV5i5TacPP4st0qAMKIWRWXPBM0UT0vUAcRTJb2OM=,iv:8utFYkRfCdOOAEdtfyYqzapy+7UUShaFXY4CRqTpaI0=,tag:5282o/d6ep54D65V0rv6fA==,type:str]
    OPENROUTER_KEY: ENC[AES256_GCM,data:3CNHFoWKvD0XMniWQLydABPWT1SB/xNbnn96VIGsqPMKg7W1rmk2TZ23Tqd77hRFCM9oig1GeJVWGoPnQXoV/1nxKfZj8svSZg==,iv:bMQFYsDjhvJ+/yffdaip2AWBEnWpjY4uuvr0laYRK3Q=,tag:wE/GdpdnO2RtBtVJZDZzIg==,type:str]
    YOUTRACK_MCP_KEY: ENC[AES256_GCM,data:wIbYvJ+ev0ca+szjMog0Qef5BuxtJ4rmLn9VaNso+0goPLdat2bJ6LLQmf9kxT3c3kyG5+Y=,iv:0F0HHoOT3ZIWB23TEcPLz1y/odXB2VTxAToVRkVLFdk=,tag:ZxexkcvUEH5kazY9sDcP3Q==,type:str]
sops:
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYUxEOVQ0VnJNdnZ0ZlQy
            YzZDc2JRNnduR0xwa2IzSXEyd3h2WVlkK0VnClJVUEh2aHlZdy9WRUZsUzBiY3My
            MjlKUThwcWJiK2JDdndqR201TEVjbUEKLS0tIG9OOVd0d0NPWnFRZmlHV0Vvbko3
            SW9zQ2V6Ti83WlAvditMNzQ1SjRoQ0kKWkFWxYqyOGWtu39EFhtaLZXV7kF8w5GB
            xATmN5XoidrePGN/FM1jDlC1uPOGW4CZ0lx3RcM6W72faQlyEi3bWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T17:06:54Z"
    mac: ENC[AES256_GCM,data:chiEf2xjsR2McWgxlNrv2JjAlcVfURDiODwvNFXxPgUzw7SCrZiYZaRFT2eyKE5v2tSBicF+gk/HxSyWtmzCqJjVhjZX69PvvUpSfHC7xc8Gek+wqHa0HG0mN+JcMMcAKutvAaNOFFgp/JI2QBt1ImTxg2AObQdcO40JsadoFC8=,iv:moU27r4fLwV7vwrduO8gN28bcfO7NsZRSqWIp3KSANM=,tag:6+MNeUIjGT+srAcp9iu2Jg==,type:str]
    pgp:
        - created_at: "2026-03-06T21:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoAQ//cVYTzW9ntY0B8dIjbKdMQaC3JzULrbhJNam1q6EeYRf6
            nS5DFMHrcLgJks89S2CgN7u9FgHrHUFxAbeXT9puCaca8rtga1Z7wzP4dhs+hAp0
            7OZXtf+g0lPtXYA+7nlYoK9opA4P450KyOkazxTROV8Vnjso5w95h3QivmQlqnJ8
            KkZBRwEBjvtIqpavuMFCHXQCV77xTDPZ/eBLsh4NxfUWLwR4qyn7UxEzb1Z4gcFB
            cNzzxI57tX6u5r7Am4z6gaexDmuyi5kgGEiYYf4B7xURWl84qce0Z6eR0N7gKybg
            aCOh9Ac5RxtOORjCntBe3dNNWmO/OVJiTxmnzeebFyrRacGw3oAQKPtoh2NhA8f/
            R4eSYtTtVNXg6c8H+pLoYut20J2JGT8bz2cOs917EsV2bK8U75PADA8nYeyiCDIh
            d4G9e2N0i+8/7ERDxVgGElCTY7lX8JP/p9Fze+L5AEZh9t6JL5XIszgpQFlJGkEj
            +M3htVfTWmzUtChY9Dm2bW14kWbOcs9FL4SVH5D8Oq/bzifCdLewOnSv3gXMFNGH
            J+GJqm90FlfVFIJRm1Om9JKAQF17W0kIAbekxdrKmKPfvh+f/ZmfL8eLDCzAMHZY
            lQVLxVu9JqYl09mtfCq/i4XueDTicH9whXm04XCdLKdvs0cNJw7j/TnG5TjYW3DS
            XgFefFxVSEBzS6QSm4LmwKLYSYxJtc7QYVsO1Hgk7XVA5yT21T118Xj4PCvYpUyb
            6IDr3QGw8PUgXupHyBp3rWgMDJGmxeGT09T4iceCEdpAusd+D+9lddsMdkgUs2A=
            =j6xJ
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
