apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox-repo
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/netbox-community/netbox-chart
  interval: 4h
