apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 4h
  chart:
    spec:
      chart: netbox
      version: 5.0.x
      sourceRef:
        kind: HelmRepository
        name: netbox-repo
        namespace: flux-system
  targetNamespace: netbox
  values:
    replicaCount: 1
    # TODO: superuser
    allowedHosts:
      - netbox.s.h-a.cc
    # TODO: email

    loginRequired: true
    remoteAuth:
      enabled: true
      backends:
        - social_core.backends.open_id_connect.OpenIdConnectAuth
    logoutRedirectUrl: "https://auth.s.h-a.cc/application/o/netbox/end-session/"

    extraConfig:
      - values:
          SOCIAL_AUTH_OIDC_ENDPOINT: "https://auth.s.h-a.cc/application/o/netbox/"
          SOCIAL_AUTH_OIDC_SCOPE: ["netbox"] # openid, profile, email added by default
          SOCIAL_AUTH_PIPELINE:
            [
              ###################
              # Default pipelines
              ###################

              # Get the information we can about the user and return it in a simple
              # format to create the user instance later. In some cases the details are
              # already part of the auth response from the provider, but sometimes this
              # could hit a provider API.
              'social_core.pipeline.social_auth.social_details',

              # Get the social uid from whichever service we're authing thru. The uid is
              # the unique identifier of the given user in the provider.
              'social_core.pipeline.social_auth.social_uid',

              # Verifies that the current auth process is valid within the current
              # project, this is where emails and domains whitelists are applied (if
              # defined).
              'social_core.pipeline.social_auth.auth_allowed',

              # Checks if the current social-account is already associated in the site.
              'social_core.pipeline.social_auth.social_user',

              # Make up a username for this person, appends a random string at the end if
              # there's any collision.
              'social_core.pipeline.user.get_username',

              # Send a validation email to the user to verify its email address.
              # Disabled by default.
              # 'social_core.pipeline.mail.mail_validation',

              # Associates the current social details with another user account with
              # a similar email address. Disabled by default.
              # 'social_core.pipeline.social_auth.associate_by_email',

              # Create a user account if we haven't found one yet.
              'social_core.pipeline.user.create_user',

              # Create the record that associates the social account with the user.
              'social_core.pipeline.social_auth.associate_user',

              # Populate the extra_data field in the social record with the values
              # specified by settings (and the default ones like access_token, etc).
              'social_core.pipeline.social_auth.load_extra_data',

              # Update the user record with any changed info from the auth service.
              'social_core.pipeline.user.user_details',


              ###################
              # Custom pipelines
              ###################
              # Set authentik Groups
              'netbox.custom_pipeline.add_groups',
              'netbox.custom_pipeline.remove_groups',
              # Set Roles
              'netbox.custom_pipeline.set_roles'
            ]
      - secret:
          secretName: netbox-sso

    extraVolumes:
      - name: netbox-sso-config
        configMap:
          name: netbox-sso-config
    extraVolumeMounts:
      - name: netbox-sso-config
        mountPath: /opt/netbox/netbox/netbox/custom_pipeline.py
        subPath: custom_pipeline.py
        readOnly: true

    releaseCheck:
      url: "https://api.github.com/repos/netbox-community/netbox/releases"
    # TODO: monitoring / metrics
    # secret key is randomly generated

    postgresql:
      enabled: false
    externalDatabase:
      host: netbox-postgres-rw.netbox
      port: 5432
      database: app
      username: app
      existingSecretName: netbox-postgres-app
      existingSecretKey: password

    redis:
      enabled: false
    tasksRedis: &redis
      host: netbox-redis.netbox
    cachingRedis: *redis

    persistence:
      enabled: true
      size: 1Gi
    # enabled when required
#    reportsPersistence:
#      enabled: true
#      size: 1Gi
#    scriptsPersistence:
#      enabled: true
#      size: 1Gi

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: netbox.s.h-a.cc
          paths: ["/"]
      tls:
        - secretName: netbox-tls
          hosts:
            - netbox.s.h-a.cc

