apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - sso-config.yaml
  - sso-secrets.yaml
  - helm-repository.yaml
  - helm.yaml
