apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-postgres
  namespace: netbox
spec:
  instances: 1
  storage:
    size: 3Gi
  backup:
    volumeSnapshot:
      className: longhorn-snapshot
      online: true
      onlineConfiguration:
        waitForArchive: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: netbox-postgres-backup
  namespace: netbox
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: netbox-postgres
  method: volumeSnapshot
  immediate: true
