apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: netbox-redis
  namespace: netbox
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.2
  # persistence is not required here
