apiVersion: v1
kind: Secret
metadata:
    name: netbox-sso
    namespace: netbox
stringData:
    oidc-authentik-secrets.yaml: ENC[AES256_GCM,data:435XXO/cPOMsFqvuGVloROT1TAciVKpn9ZIrrAiwzMG3xW2oI3QSIjmEvvOPpSErRGVgxFZ0/k9S3jgQqVNJeQYZiiE0GOO9+Y4m6c/V8zoqWfPWbkD4jDSD3yMkJNhsYsDlo5ayYhdAHfAR0GTshF2Eq+z2IoQa9p642pZjqJIN17H+eCJDrDIdTSEjYPZp7UkeKkKveV/zBnuiIejvD0/1uX4NNOJtlC61lIq+cjCgSMZcNu8u4Sg95Fk8Zscl44Qf3CRZnGKl2Hs1I1/AhbVF4UraIP9fEQ==,iv:9yf3pbYLvPId4fEwPSPetVWZJgJIN3sUIQ/Gc80E5u0=,tag:cws0+r9UH7xdtv4h5Yn95w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kvurr9559cqq6q05gdv0g7798darr2y0n857zjz7z6w34cvx2f0s4auuwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQmZiVm1JZmFXRVhjSEZW
            NlJWTVdMc2RhYy9iWmo1Ylh4SjRYcVR0WmxNCmphUE9LdUtEbWZYQkJzcDluUXZx
            RmV6WElnK1M2WTJEU2J3NXE3NVg1UGcKLS0tIHV1SXlONnpZcUdweGlUL1Y4RzFp
            WnhXdmZjSGczYTRRaUE4WU9nZFdEMTQKfxyvbCuPTBFtWwoWXDrMee02NvyOR356
            UFiaSz1fAapNCPHg9gNWbDm5Y1DVhleraYs6Zjb0jgmGhzUU+qwVGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T21:23:53Z"
    mac: ENC[AES256_GCM,data:IKqSomoQ+Th1ChbEn+P/OijDpmtNI3YXCzFhgeTgdXRFUEWTWzgUClZoCU/JAXj0G4MdRE+uGSodtKJc0whRbEAMugJEYx5F+TeN3/JrEN/TVXcDo4pppBfURdjP9l8WZwciRqFE7xu79LO4+PzHAdC3GPkywQwZFGZ9fuv/rGg=,iv:AmMuZFUYqFGxPuAd12WNtgFZ3dzFJxn+mub9L7P/Wfc=,tag:tWVnn8Ixs0EiR7wClKzAYg==,type:str]
    pgp:
        - created_at: "2025-04-24T21:23:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4DsoDiMz+AoAQ/8DfTLmz2/cngx+hYY5T03YiXwQBKZwI6TKmmFmO4SSExD
            ykRmzlx9nEvrfOdGuKg3rfpfoJXTEyDcppg0ktIROgb5XSq5IXumnElnsnAvqvKn
            ZV1usaYJd9s2NFcvela2rJjooAdbV3KA0Z5rKsQD4bqF4gUyNl9UBjhK02ULu03x
            YsTg9AMYTAhzanqzPmoTdKwDB8SxO+TUQ83bmfjAbXYKou7Z80dUvlWlp0HjGOPo
            C2ClO4VxGa7C1n0CuygvI15v03CB7zr0W+ZeNVacmwKovPH/xajxLTIo9BUT4i0B
            QKcEE0Ex4VZudkZMd5s/kx+V2n9ZknKSJrBP1ad3i5scvDYZGkYoCmR4uwq0vPXW
            4+0Cv0OtUXRk5s/BRrTEtD0Oi1kVWV3ShV1Q15bqOQn+8LbMaKmGHarM2ZbeobpM
            OReVHPR5akziBwQVkIs03z8BpU37rgPW396VJRoPDmv0dPqEEc7u0M4jvN4s7lSQ
            z8sMPYIzCq90ikzS4y4UHu6yL4o0UlBYt4Ny2wA/YoOqg1efaHCQpp/KMm4ZDyBH
            6oFiOPyxXnOdnsDk6/mEzC/FERTVLARYiUNdUPQDDrUMQmRbeCNHCDWnEo5S5iwC
            w/c1bzMmhGc6xoH9M1l/bvvf7TPiiMASEV91evIwQalLUuZXBOtvjTyqcx6W7/vS
            XgEKaOcXECZEW5x7iaW/H+oPcY2vqT9rzfsxIpAsYe5uxoFqR8XK0CPz97vR6beO
            bZj7y7QUquzHgpKBBCpcj+HPEELLd5FD7grR3tX58012DB0OViEZdvbsE0MVN+o=
            =L1g6
            -----END PGP MESSAGE-----
          fp: 9264180E8BA8C283F19DB9F8B18AC2562696539F
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
