apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-postgres
spec:
  instances: 1
  storage:
    size: 2Gi
  backup:
    volumeSnapshot:
      className: longhorn-snapshot
      online: true
      onlineConfiguration:
        waitForArchive: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: freshrss-postgres-backup
  namespace: freshrss
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: freshrss-postgres
  method: volumeSnapshot
  immediate: true
