clusterName: krz-k8s

talosVersion: v1.6.7
kubernetesVersion: v1.29.0

allowSchedulingOnControlPlanes: false

endpoint: https://talos-master-1.lan:6443

nodes:
  - hostname: talos-master-1.lan
    ipAddress: 10.0.0.150
    controlPlane: true
    installDiskSelector:
      size: 20Gi

  - hostname: talos-worker-1.lan
    ipAddress: 10.0.0.151
    installDiskSelector:
      size: 20Gi

  - hostname: talos-worker-2.lan
    ipAddress: 10.0.0.152
    installDiskSelector:
      size: 20Gi
