clusterName: krz-k8s

talosVersion: v1.7.5
kubernetesVersion: v1.29.0

allowSchedulingOnControlPlanes: false

endpoint: https://talos-master-1.lan:6443

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: talos-master-1.lan
    ipAddress: 10.0.0.150
    controlPlane: true
    installDiskSelector:
      size: 20Gi

  - hostname: talos-worker-1.lan
    ipAddress: 10.0.0.151
    installDiskSelector:
      size: 20Gi

  - hostname: talos-worker-2.lan
    ipAddress: 10.0.0.152
    installDiskSelector:
      size: 20Gi
