clusterName: krz-k8s

talosVersion: v1.9.1
kubernetesVersion: v1.29.0

allowSchedulingOnControlPlanes: false

endpoint: https://talos-master-1.lan:6443

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          # longhorn required iscsi-tools and util-linux-tools
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw

nodes:
  - hostname: talos-master-1.lan
    ipAddress: 10.0.0.150
    controlPlane: true
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-1.lan
    ipAddress: 10.0.0.151
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-2.lan
    ipAddress: 10.0.0.152
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-01.talos.homelab.oraclevcn.com
    ipAddress: 10.72.10.101
    installDiskSelector:
      size: ">10G"
    nodeLabels:
      network-location: oracle
    machineSpec:
      arch: arm64
      bootMethod: disk-image
      imageSuffix: qcow2
      mode: oracle
    imageSchematic:
      customization:
        systemExtensions:
          officialExtensions: [] # TODO: add oracle specific extensions
    patches:
      - |-
        machine:
          time:
            servers:
              - 169.254.169.254
