clusterName: krz-k8s

talosVersion: v1.7.6
kubernetesVersion: v1.29.0

allowSchedulingOnControlPlanes: false

endpoint: https://talos-master-1.lan:6443

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          # longhorn required iscsi-tools and util-linux-tools
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw

nodes:
  - hostname: talos-master-1.lan
    ipAddress: 10.0.0.150
    controlPlane: true
    installDiskSelector:
      size: 20Gi
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-1.lan
    ipAddress: 10.0.0.151
    installDiskSelector:
      size: 20Gi
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-2.lan
    ipAddress: 10.0.0.152
    installDiskSelector:
      size: 20Gi
    nodeLabels:
      network-location: krz
