# noinspection YAMLSchemaValidation
#$schema: https://raw.githubusercontent.com/budimanjojo/talhelper/refs/heads/master/pkg/config/schemas/talconfig.json

clusterName: krz-k8s

talosVersion: v1.11.3
kubernetesVersion: v1.34.1

allowSchedulingOnControlPlanes: false

endpoint: https://talos-master-1.lan:6443

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        network:
          kubespan:
            enabled: true
            allowDownPeerBypass: true

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          # longhorn requires iscsi-tools and util-linux-tools
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        network:
          kubespan:
            enabled: true
            allowDownPeerBypass: true
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw

nodes:
  - hostname: talos-master-1.lan
    ipAddress: 10.0.0.150
    controlPlane: true
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-1.lan
    ipAddress: 10.0.0.151
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz

  - hostname: talos-worker-2.lan
    ipAddress: 10.0.0.152
    installDiskSelector:
      model: "QEMU HARDDISK"
    nodeLabels:
      network-location: krz
