apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-network-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.200-10.0.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-network-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - main-network-pool
