apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backup-default
  namespace: longhorn-system
spec:
  cron: "0 0 * * *"
  task: "backup"
  groups:
    - default
  retain: 2
  concurrency: 1
  labels:
    job: daily-backup-default
