apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
