apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  source:
    chart: csi-driver-nfs
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.6.0
    helm:
      releaseName: csi-driver-nfs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
