apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin-server
  labels:
    app: atuin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atuin-server
  template:
    metadata:
      name: atuin-server
      labels:
        app: atuin-server
    spec:
      containers:
        - name: atuin-server
          image: ghcr.io/atuinsh/atuin:v18.12.0
          args:
            - start
          env:
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: atuin-postgres-app
                  key: uri
            - name: ATUIN_HOST
              value: 0.0.0.0
            - name: ATUIN_PORT
              value: "8080"
            - name: ATUIN_OPEN_REGISTRATION
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 250m
              memory: 1Gi
